[package]
name = "mini-bank-ui"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = "0.8.0-beta.4"
wee_alloc = "0.4.5"
